// pages/index.js
import React from 'react';
import ProductCard from "@components/productcard";

const Page = () => {
  
const products = [
  {
    id: 1,
    productImage: '/BananaFibrePlate.png',
    productName: 'Banana Fibre Plate',
    description: 'Customization Available',
    category: "loveOfOurLadies",
      quantity1: null,
      price1: 11,
      quantity1Unit: "g",
      quantity2: null,
      price2: 11,
      quantity2Unit: "g",
      quantity3: null,
      price3: 8,
      quantity3Unit: "g",
      isOrganic: true,
      isAvailableOn: true,
  },
  {
    id: 2,
    productImage: '/BasketWithLid.png',
    productName: 'Handmade Basket With Lid',
    description: 'Customization Available',
    category: "loveOfOurLadies",
      quantity1: null,
      price1: 11,
      quantity1Unit: "g",
      quantity2: null,
      price2: 11,
      quantity2Unit: "g",
      quantity3: null,
      price3: 8,
      quantity3Unit: "g",
      isOrganic: true,
      isAvailableOn: true,
  },
  {
    id: 3,
    productImage: '/CircularDecorativeBasket-removebg-preview.png',
    productName: 'Handmade Circular Decorative Basket',
    description: 'Customization Available',
    category: "loveOfOurLadies",
      quantity1: null,
      price1: 11,
      quantity1Unit: "g",
      quantity2: null,
      price2: 11,
      quantity2Unit: "g",
      quantity3: null,
      price3: 8,
      quantity3Unit: "g",
      isOrganic: true,
      isAvailableOn: true,
  },
  {
    id: 4,
    productImage: '/CircularDeepMultipurpose.png',
    productName: 'Handmade Circular Deep Multipurpose Basket',
    description: 'Customization Available',
    category: "loveOfOurLadies",
      quantity1: null,
      price1: 11,
      quantity1Unit: "g",
      quantity2: null,
      price2: 11,
      quantity2Unit: "g",
      quantity3: null,
      price3: 8,
      quantity3Unit: "g",
      isOrganic: true,
      isAvailableOn: true,
  },
  {
    id: 5,
    productImage: '/CircularFiberHamper-removebg-preview.png',
    productName: 'Circular Banana Fiber Basket',
    description: 'Customization Available',
    category: "loveOfOurLadies",
      quantity1: null,
      price1: 11,
      quantity1Unit: "g",
      quantity2: null,
      price2: 11,
      quantity2Unit: "g",
      quantity3: null,
      price3: 8,
      quantity3Unit: "g",
      isOrganic: true,
      isAvailableOn: true,
  },
  {
    id: 6,
    productImage: '/DecorativeDeepBananaFabricBasket.png',
    productName: 'Decorative Deep Handmade Basket',
    description: 'Customization Available',
    category: "loveOfOurLadies",
      quantity1: null,
      price1: 11,
      quantity1Unit: "g",
      quantity2: null,
      price2: 11,
      quantity2Unit: "g",
      quantity3: null,
      price3: 8,
      quantity3Unit: "g",
      isOrganic: true,
      isAvailableOn: true,
  },
  {
    id: 7,
    productImage: '/FruitandVegBasket-removebg-preview.png',
    productName: 'Fruit/Vegetable Holder Banana Fibre Basket',
    description: 'Customization Available',
    category: "loveOfOurLadies",
      quantity1: null,
      price1: 11,
      quantity1Unit: "g",
      quantity2: null,
      price2: 11,
      quantity2Unit: "g",
      quantity3: null,
      price3: 8,
      quantity3Unit: "g",
      isOrganic: true,
      isAvailableOn: true,
  },
  {
    id: 8,
    productImage: '/FruitAndVegBasketWithHandle.png',
    productName: 'Fruit/Vegetable Holder Handmade Basket with Handle',
    description: 'Customization Available',
    category: "loveOfOurLadies",
      quantity1: null,
      price1: 11,
      quantity1Unit: "g",
      quantity2: null,
      price2: 11,
      quantity2Unit: "g",
      quantity3: null,
      price3: 8,
      quantity3Unit: "g",
      isOrganic: true,
      isAvailableOn: true,
  },
  {
    id: 3,
    productImage: '/LampHolder.png',
    productName: 'Handmade Lamp Holder',
    description: 'Customization Available',
    category: "loveOfOurLadies",
      quantity1: null,
      price1: 11,
      quantity1Unit: "g",
      quantity2: null,
      price2: 11,
      quantity2Unit: "g",
      quantity3: null,
      price3: 8,
      quantity3Unit: "g",
      isOrganic: true,
      isAvailableOn: true,
  },
  {
    id: 4,
    productImage: '/OvalFruitAndVegBasketWithHandle.png',
    productName: 'Handmade Oval Fruit/VegBasket With Handle',
    description: 'Customization Available',
    category: "loveOfOurLadies",
      quantity1: null,
      price1: 11,
      quantity1Unit: "g",
      quantity2: null,
      price2: 11,
      quantity2Unit: "g",
      quantity3: null,
      price3: 8,
      quantity3Unit: "g",
      isOrganic: true,
      isAvailableOn: true,
  },

  {
    id: 3,
    productImage: '/SquareDeepMultipurpose.png',
    productName: 'Handmade Square Deep Multipurpose',
    description: 'Customization Available',
    category: "loveOfOurLadies",
      quantity1: null,
      price1: 11,
      quantity1Unit: "g",
      quantity2: null,
      price2: 11,
      quantity2Unit: "g",
      quantity3: null,
      price3: 8,
      quantity3Unit: "g",
      isOrganic: true,
      isAvailableOn: true,
  },
  {
    id: 4,
    productImage: '/TallBlanketBasket.png',
    productName: 'Handmade Tall Blanket Basket',
    description: 'Customization Available',
    category: "loveOfOurLadies",
      quantity1: null,
      price1: 11,
      quantity1Unit: "g",
      quantity2: null,
      price2: 11,
      quantity2Unit: "g",
      quantity3: null,
      price3: 8,
      quantity3Unit: "g",
      isOrganic: true,
      isAvailableOn: true,
  },
  {
    id: 6,
    productImage: '/DecorativeDeepBananaFabricBasket.png',
    productName: 'Decorative Deep Banana Fabric Basket ',
    description: 'Customization Available',
    category: "loveOfOurLadies",
      quantity1: null,
      price1: 11,
      quantity1Unit: "g",
      quantity2: null,
      price2: 11,
      quantity2Unit: "g",
      quantity3: null,
      price3: 8,
      quantity3Unit: "g",
      isOrganic: true,
      isAvailableOn: true,
  },
];

  return (
    <div>
      <h1 className="text-2xl font-semibold my-4">Love of Our Ladies</h1>
      <img src='/Basket_Weaving_Coloring_Page_Sketch_Coloring_Page-removebg-preview.png' alt="Temple Image" className="h-96 w-96 lg:hidden mx-auto" />
      {products.map((product) => (
        <ProductCard key={product.id} {...product} />
      ))}
    </div>
  );
};

export default Page;
