// pages/index.js
"use client"
import React from 'react';
import ProductCard from "@components/productcard";

const Page = () => {
  const products = [
    {
      id: 1,
      productImage: '/Ponni-Rice.jpg',
      productName: "Rice",
      description: "asas",
      category: "Farmers",
      quantity1: null,
      price1: 11,
      quantity1Unit: "g",
      quantity2: null,
      price2: 11,
      quantity2Unit: "g",
      quantity3: null,
      price3: 8,
      quantity3Unit: "g",
      isOrganic: true,
      isAvailableOn: true,
    },
    {
      id: 2,
      productImage: '/Black-gram.jpg',
      productName: "Black Gram",
      description: "asas",
      category: "Farmers",
      quantity1: null,
      price1: 11,
      quantity1Unit: "g",
      quantity2: null,
      price2: 11,
      quantity2Unit: "g",
      quantity3: null,
      price3: 8,
      quantity3Unit: "g",
      isOrganic: true,
      isAvailableOn: true,
    },
    {
      id: 3,
      productImage: '/Henna-Powder.jpg',
      productName: 'Henna Powder',
      description: "asas",
      category: "Farmers",
      quantity1: null,
      price1: 11,
      quantity1Unit: "g",
      quantity2: null,
      price2: 11,
      quantity2Unit: "g",
      quantity3: null,
      price3: 8,
      quantity3Unit: "g",
      isOrganic: true,
      isAvailableOn: true,
    },
    {
      id: 4,
      productImage: '/Honey.png',
      productName: 'Organic Honey',
      description: "asas",
      category: "Farmers",
      quantity1: null,
      price1: 11,
      quantity1Unit: "g",
      quantity2: null,
      price2: 11,
      quantity2Unit: "g",
      quantity3: null,
      price3: 8,
      quantity3Unit: "g",
      isOrganic: true,
      isAvailableOn: true,
    },
    {
      id: 5,
      productImage: '/Neem-Powder.jpg',
      productName: 'Neem Powder',
      description: "asas",
      category: "Farmers",
      quantity1: null,
      price1: 11,
      quantity1Unit: "g",
      quantity2: null,
      price2: 11,
      quantity2Unit: "g",
      quantity3: null,
      price3: 8,
      quantity3Unit: "g",
      isOrganic: true,
      isAvailableOn: true,
    },
    {
      id: 6,
      productImage: '/Curry-Leaves-Powder.jpg',
      productName: 'Curry Leaves Powder',
      description: "asas",
      category: "Farmers",
      quantity1: null,
      price1: 11,
      quantity1Unit: "g",
      quantity2: null,
      price2: 11,
      quantity2Unit: "g",
      quantity3: null,
      price3: 8,
      quantity3Unit: "g",
      isOrganic: true,
      isAvailableOn: true,
    },
    {
      id: 7,
      productImage: '/Moringa-Powder.jpg',
      productName: 'Moringa Powder',
      description: "asas",
      category: "Farmers",
      quantity1: null,
      price1: 11,
      quantity1Unit: "g",
      quantity2: null,
      price2: 11,
      quantity2Unit: "g",
      quantity3: null,
      price3: 8,
      quantity3Unit: "g",
      isOrganic: true,
      isAvailableOn: true,
    },
  ];
  return (
    <div>
      <h1 className="text-2xl font-semibold my-4">From Farmers</h1>
      <img src='/From-Farmers-All-Product-page-image.png' alt="Leelavathi" className="h-96 w-96 lg:hidden mx-auto" />
      {products.map((product) => (
        <ProductCard key={product.id} {...product} />
      ))}
    </div>
  );
};

export default Page;
